// src/components/layout/Navbar.tsx
import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Menu, X, LogOut, User, LayoutGrid } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import Button from '../ui/Button';
import { NAVIGATION_LINKS } from '../../constants/data';
import { useAuth } from '../../context/AuthContext';

const Navbar = () => {
  const [isScrolled, setIsScrolled] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [userMenuOpen, setUserMenuOpen] = useState(false);
  const navigate = useNavigate();
  const { isLoggedIn, user, logout } = useAuth();

  useEffect(() => {
    const handleScroll = () => setIsScrolled(window.scrollY > 20);
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToSection = (href: string) => {
    setIsMobileMenuOpen(false);
    const element = document.querySelector(href);
    if (element) element.scrollIntoView({ behavior: 'smooth' });
  };

  const handleLogout = () => {
    logout();
    setUserMenuOpen(false);
    navigate('/');
  };

  return (
    <motion.nav
      initial={{ y: -100 }}
      animate={{ y: 0 }}
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        isScrolled ? 'bg-white/80 backdrop-blur-lg shadow-sm border-b border-border' : 'bg-transparent'
      }`}
    >
      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        <div className="flex items-center justify-between h-20">
          {/* Logo */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="flex items-center gap-2 cursor-pointer"
            onClick={() => scrollToSection('#home')}
          >
            <div className="w-10 h-10 bg-gradient-to-br from-primary to-primary/80 rounded-xl flex items-center justify-center">
              <span className="text-white font-bold text-xl">YQ</span>
            </div>
            <span className="text-2xl font-bold text-text">YA QUEDÓ</span>
          </motion.div>

          {/* Desktop Navigation */}
          <div className="hidden lg:flex items-center gap-8">
            {NAVIGATION_LINKS.map((link, index) => (
              <motion.button
                key={link.name}
                initial={{ opacity: 0, y: -10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                onClick={() => scrollToSection(link.href)}
                className="text-muted hover:text-text transition-colors font-medium"
              >
                {link.name}
              </motion.button>
            ))}
          </div>

          {/* Desktop CTA */}
          <div className="hidden lg:flex items-center gap-4 relative">
            {isLoggedIn ? (
              <>
                <Button variant="ghost" size="md" onClick={() => navigate('/catalog')}>
                  <LayoutGrid size={16} className="mr-2" /> Catálogo
                </Button>
                <div className="relative">
                  <button
                    onClick={() => setUserMenuOpen(v => !v)}
                    className="flex items-center gap-2 bg-background hover:bg-border/60 rounded-xl px-3 py-2 transition-colors"
                  >
                    <div className="w-7 h-7 bg-primary rounded-full flex items-center justify-center">
                      <span className="text-white font-bold text-xs">{user?.firstName?.charAt(0)}</span>
                    </div>
                    <span className="text-sm font-medium text-text">{user?.firstName}</span>
                  </button>
                  {userMenuOpen && (
                    <div className="absolute right-0 top-12 w-48 bg-white rounded-2xl shadow-xl border border-border py-2 z-50">
                      <button onClick={() => { navigate('/profile'); setUserMenuOpen(false); }} className="w-full flex items-center gap-3 px-4 py-2 text-sm text-text hover:bg-background transition-colors">
                        <User size={14} className="text-muted" /> Mi perfil
                      </button>
                      <div className="border-t border-border my-1" />
                      <button onClick={handleLogout} className="w-full flex items-center gap-3 px-4 py-2 text-sm text-red-600 hover:bg-red-50 transition-colors">
                        <LogOut size={14} /> Cerrar sesión
                      </button>
                    </div>
                  )}
                </div>
              </>
            ) : (
              <>
                <Button variant="ghost" size="md" onClick={() => navigate('/login')}>
                  Iniciar sesión
                </Button>
                <Button variant="primary" size="md" onClick={() => navigate('/register')}>
                  Comenzar
                </Button>
              </>
            )}
          </div>

          {/* Mobile Menu Button */}
          <button
            className="lg:hidden p-2 rounded-lg hover:bg-background transition-colors"
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            aria-label="Alternar menú"
          >
            {isMobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
          </button>
        </div>
      </div>

      {/* Mobile Menu */}
      <AnimatePresence>
        {isMobileMenuOpen && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className="lg:hidden bg-white border-b border-border overflow-hidden"
          >
            <div className="px-6 py-4 space-y-4">
              {NAVIGATION_LINKS.map((link) => (
                <button
                  key={link.name}
                  onClick={() => scrollToSection(link.href)}
                  className="block w-full text-left py-2 text-text font-medium hover:text-primary transition-colors"
                >
                  {link.name}
                </button>
              ))}
              <div className="pt-4 space-y-3">
                {isLoggedIn ? (
                  <>
                    <Button variant="outline" size="md" className="w-full" onClick={() => { navigate('/catalog'); setIsMobileMenuOpen(false); }}>
                      <LayoutGrid size={16} className="mr-2" /> Catálogo
                    </Button>
                    <Button variant="outline" size="md" className="w-full" onClick={() => { navigate('/profile'); setIsMobileMenuOpen(false); }}>
                      <User size={16} className="mr-2" /> Mi perfil
                    </Button>
                    <Button variant="ghost" size="md" className="w-full text-red-600" onClick={handleLogout}>
                      <LogOut size={16} className="mr-2" /> Cerrar sesión
                    </Button>
                  </>
                ) : (
                  <>
                    <Button variant="outline" size="md" className="w-full" onClick={() => { navigate('/login'); setIsMobileMenuOpen(false); }}>
                      Iniciar sesión
                    </Button>
                    <Button variant="primary" size="md" className="w-full" onClick={() => { navigate('/register'); setIsMobileMenuOpen(false); }}>
                      Comenzar
                    </Button>
                  </>
                )}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.nav>
  );
};

export default Navbar;

// frontend/src/app/components/navbar/navbar.component.ts
import { Component, HostListener, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './navbar.component.html',
})
export class NavbarComponent {
  menuOpen = false;
  scrolled = signal(false);

  constructor(public authService: AuthService) {}

  @HostListener('window:scroll')
  onWindowScroll(): void {
    this.scrolled.set(window.scrollY > 8);
  }

  logout(): void {
    this.authService.logout();
    this.menuOpen = false;
  }
}

<nav
  class="fixed top-0 left-0 right-0 z-50 transition-all duration-300"
  [class]="scrolled() || menuOpen
    ? 'fixed top-0 left-0 right-0 z-50 transition-all duration-300 bg-white/80 backdrop-blur-xl border-b border-gray-200/70 shadow-soft'
    : 'fixed top-0 left-0 right-0 z-50 transition-all duration-300 bg-transparent border-b border-transparent'"
>
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <!-- Logo -->
      <a routerLink="/" class="flex items-center gap-2.5 group focus:outline-none focus-visible:ring-4 focus-visible:ring-blue-600/15 rounded-xl">
        <div class="w-9 h-9 bg-gradient-to-br from-blue-600 to-blue-700 rounded-xl flex items-center justify-center shadow-soft transition-transform duration-300 group-hover:scale-105">
          <span class="text-white font-bold text-base">YQ</span>
        </div>
        <span class="text-lg font-bold tracking-tight text-gray-900">YA QUEDÓ</span>
      </a>

      <!-- Desktop Nav -->
      <div class="hidden md:flex items-center gap-2">
        <a
          routerLink="/"
          routerLinkActive="text-blue-600 bg-blue-50/70"
          [routerLinkActiveOptions]="{ exact: true }"
          class="text-gray-600 hover:text-gray-900 hover:bg-gray-100/70 font-medium text-sm px-4 py-2 rounded-xl transition-all duration-200 focus:outline-none focus-visible:ring-4 focus-visible:ring-blue-600/15"
        >
          Inicio
        </a>
        <a
          routerLink="/catalog"
          routerLinkActive="text-blue-600 bg-blue-50/70"
          class="text-gray-600 hover:text-gray-900 hover:bg-gray-100/70 font-medium text-sm px-4 py-2 rounded-xl transition-all duration-200 focus:outline-none focus-visible:ring-4 focus-visible:ring-blue-600/15"
        >
          Catálogo
        </a>

        @if (authService.isLoggedIn()) {
          <a
            routerLink="/assistant"
            routerLinkActive="text-indigo-600 bg-indigo-50/70"
            class="text-gray-600 hover:text-indigo-600 hover:bg-indigo-50/50 font-medium text-sm px-4 py-2 rounded-xl transition-all duration-200 flex items-center gap-1.5 focus:outline-none focus-visible:ring-4 focus-visible:ring-indigo-600/15"
          >
            <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456z"/>
            </svg>
            Asistente IA
          </a>
          <a
            routerLink="/profile"
            routerLinkActive="text-blue-600 bg-blue-50/70"
            class="text-gray-600 hover:text-gray-900 hover:bg-gray-100/70 font-medium text-sm px-4 py-2 rounded-xl transition-all duration-200 focus:outline-none focus-visible:ring-4 focus-visible:ring-blue-600/15"
          >
            Mi perfil
          </a>

          <!-- User dropdown -->
          <div class="relative ml-2">
            <button
              (click)="menuOpen = !menuOpen"
              class="flex items-center gap-2 bg-white/70 hover:bg-gray-100 border border-gray-200/70 rounded-xl px-3 py-2 transition-all duration-200 shadow-soft focus:outline-none focus-visible:ring-4 focus-visible:ring-blue-600/15"
              aria-haspopup="menu"
              [attr.aria-expanded]="menuOpen"
            >
              <div class="w-7 h-7 bg-gradient-to-br from-blue-600 to-blue-700 rounded-full flex items-center justify-center">
                <span class="text-white font-semibold text-xs">
                  {{ authService.currentUser()?.firstName?.charAt(0) }}
                </span>
              </div>
              <span class="text-sm font-medium text-gray-700">
                {{ authService.currentUser()?.firstName }}
              </span>
              <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-gray-400 transition-transform duration-200" [class.rotate-180]="menuOpen" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
              </svg>
            </button>

            @if (menuOpen) {
              <div class="absolute right-0 mt-3 w-52 bg-white rounded-2xl shadow-float border border-gray-100 py-2 z-50 animate-scale-in origin-top-right">
                <a routerLink="/profile" (click)="menuOpen = false" class="flex items-center gap-3 px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-50 transition-colors">
                  <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/>
                  </svg>
                  Mi perfil
                </a>
                <div class="border-t border-gray-100 my-1"></div>
                <button (click)="logout()" class="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-red-600 hover:bg-red-50 transition-colors">
                  <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"/>
                  </svg>
                  Cerrar sesión
                </button>
              </div>
            }
          </div>
        } @else {
          <div class="flex items-center gap-2 ml-4">
            <a routerLink="/login" class="btn-ghost text-sm">Iniciar sesión</a>
            <a routerLink="/register" class="btn-primary text-sm">Crear cuenta</a>
          </div>
        }
      </div>

      <!-- Mobile menu button -->
      <button (click)="menuOpen = !menuOpen" aria-label="Abrir menú" class="md:hidden p-2.5 rounded-xl text-gray-600 hover:bg-gray-100 transition-colors focus:outline-none focus-visible:ring-4 focus-visible:ring-blue-600/15">
        @if (menuOpen) {
          <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
          </svg>
        } @else {
          <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
          </svg>
        }
      </button>
    </div>
  </div>

  <!-- Mobile Menu -->
  @if (menuOpen) {
    <div class="md:hidden bg-white/95 backdrop-blur-xl border-t border-gray-100 px-4 py-5 space-y-1.5 animate-fade-in shadow-card">
      <a routerLink="/" (click)="menuOpen = false" class="block px-4 py-3 rounded-xl text-gray-700 hover:bg-gray-50 font-medium text-sm transition-colors">
        Inicio
      </a>
      <a routerLink="/catalog" (click)="menuOpen = false" class="block px-4 py-3 rounded-xl text-gray-700 hover:bg-gray-50 font-medium text-sm transition-colors">
        Catálogo
      </a>
      @if (authService.isLoggedIn()) {
        <a routerLink="/assistant" (click)="menuOpen = false" class="block px-4 py-3 rounded-xl text-indigo-700 bg-indigo-50 hover:bg-indigo-100 font-semibold text-sm transition-colors">
          ✨ Asistente IA
        </a>
        <a routerLink="/profile" (click)="menuOpen = false" class="block px-4 py-3 rounded-xl text-gray-700 hover:bg-gray-50 font-medium text-sm transition-colors">
          Mi perfil
        </a>
        <button (click)="logout()" class="w-full text-left px-4 py-3 rounded-xl text-red-600 hover:bg-red-50 font-medium text-sm transition-colors">
          Cerrar sesión
        </button>
      } @else {
        <a routerLink="/login" (click)="menuOpen = false" class="block px-4 py-3 rounded-xl text-gray-700 hover:bg-gray-50 font-medium text-sm transition-colors">
          Iniciar sesión
        </a>
        <a routerLink="/register" (click)="menuOpen = false" class="block px-4 py-3 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-semibold text-sm text-center transition-colors">
          Crear cuenta
        </a>
      }
    </div>
  }
</nav>

<!-- Spacer for fixed navbar -->
<div class="h-16"></div>
